[package]
name = "irssi-wire"
version = "0.1.0"
authors = ["Henrik Böving <hargonix@gmail.com>"]
edition = "2018"
license = "MIT"

[build-dependencies]
bindgen = "0.50"

[lib]
crate-type = ["dylib"]

[dependencies]
