name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Irssi, bindgen and protobuf dependencies
      run: sudo apt install libglib2.0-dev libssl-dev perl libncurses5-dev libncursesw5-dev protobuf-compiler llvm-dev clang
    - name: Build Irssi
      run: git clone https://github.com/irssi/irssi && cd irssi && ./autogen.sh && ./configure && make && cd ..
    - name: Build irssi-wire
      run: IRSSI_INCLUDE=irssi cargo build --verbose
    - name: Run tests
      run: IRSSI_INCLUDE=irssi cargo test --verbose
